### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by steffenagger** [jdavisclark/jsformat-atom#61]
Whenever i run `Jsformat: Format` in any file, I get the following (tried uninstalling/reinstalling & removing settings from config.cson - anything else I should try?) :

(btw, I'm a little new to Atom)

_Uncaught TypeError: undefined is not a function_

_~/.atom/packages/jsformat/lib/format.coffee:153_

_TypeError: undefined is not a function
  at Object.module.exports.displayUnsupportedLanguageNotification (/Users/sua/.atom/packages/jsformat/lib/format.coffee:153:40)
  at Object.module.exports.format (/Users/sua/.atom/packages/jsformat/lib/format.coffee:33:8)
  at atom-workspace.<anonymous> (/Users/sua/.atom/packages/jsformat/lib/format.coffee:14:64)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)_

**Comment by ilanbiala** [comment]
You have to set the language to JSON/JavaScript.

**Comment by kokujin** [comment]
Is anybody else having having this issue? As soon as I install the jinja, Twig or Nunjucks language syntax, jsFormat emits the above mentioned  stacktrace and does not work anymore .

**Comment by ilanbiala** [comment]
Those are not supported languages, please don't try to use JSFormat with them. As for the error, a PR can fix that and prevent JSFormat from not working after.

**Comment by kokujin** [comment]
The problem is actually that the errors are thrown immediately and automatically by jsformat, These templating languages are definitely not JS, so I do not use jsformat on them

**Comment by ilanbiala** [comment]
@kokujin yours is a different issue than this one. This is when JSFormat is run, and I've never heard of or had any issues with JSFormat automatically doing something. Have you tried uninstalling?

**Comment by kokujin** [comment]
This is definitely a bug. JSFormat has a setting called "format on save". This function should only be triggered if the language syntax is set to "javascript" and not when the file suffix is ".js"

**Comment by ilanbiala** [comment]
Still an issue?

**Comment by kokujin** [comment]
I will check if this is still the case by enabling "format on save " again. Has there been a bugfix?

**Comment by steffenagger** [comment]
Hey guys, I'm not using Atom anymore, so won't be any help on this.
Feel free to close the issue whenever.

**Comment by steffenagger** [comment]
Think this is outdated?
